# Netlify configuration file

# Build settings
[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command
  command = "npm install && npm run build:mfe"

# Redirects and rewrites for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  # Add your environment variables here if needed
  VITE_PUBLIC_API_URL = "https://api.shoppingcart.dev/api/v1"
  VITE_PUBLIC_MODE = "LOCAL"
  NODE_VERSION = "22"

# Optional: Headers to configure
[[headers]]
  # Define which paths get these headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Enable CORS
    Access-Control-Allow-Origin = "*"
